language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-7 
            - g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7

    - os: linux
      dist: xenial
      compiler: clang

before_install:
 - eval "${MATRIX_EVAL}"
 - sudo apt install qt5-default
 
script:
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build . --config RELEASE
  - cd ..
